### ISSUE TITLE
LQFP package pads narrower than leads

### ISSUE THREAD

**Issue by ii8** [LibrePCB-Libraries/LibrePCB_Base.lplib#103]
For some LQFP packages like LQFP50P1200X1200X140-64 for example the pad width is 0.2mm but the lead width is 0.22mm. Is that really what the IPC standard says? Most manufacturers recommend 0.3mm width pads.

**Comment by ii8** [comment]
I guess it does say that:
![image](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/5731567/49b90a43-139f-4e4f-b9fc-a77959a49b85)
But in that case shouldn't Density level A pads be wider than the leads, they are currently the same width.

**Comment by ubruhin** [comment]
Without taking a look at the relevant generator code yet, I agree this sounds wrong!

**Comment by ubruhin** [comment]
Hm it seems this is actually indeed what IPC recommends, respectively the Library Expert: https://www.pcblibraries.com/Products/FPX/UserGuide/download/Footprint%20Expert%20Surface%20Mount%20Families.pdf

So I think the footprints are correct, although it looks a bit strange. So I'll close this issue for now. But if there is any problem (e.g. with soldering), please let me know.
