### ISSUE TITLE
Incorrect designation on NPN & PNP transistors

### ISSUE THREAD

**Issue by Akao-dev** [LibrePCB-Libraries/LibrePCB_Base.lplib#104]
Designation letter should be Q (for all transistor types). T is reserved for transformers.
![incorrect-designation](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/143131755/9883600d-80f5-42ab-a9f2-c9845e531d65)

**Comment by dbrgn** [comment]
IEEE agrees with you.
