### ISSUE TITLE
Missing inductors

### ISSUE THREAD

**Issue by eto-** [LibrePCB-Libraries/LibrePCB_Base.lplib#134]
I realized that there are no inductors in the base library.

Can you add the Package categories Chip Inductor and Through-Hole Inductor?
The chip inductors can be probably generated by the generate_chip.py script with some small fixes. I'm not expert enough in the internal details to modify it. The standard chip inductors are 0402,0603 and 0805 (imperial): I've never seen smaller.

**Comment by ubruhin** [comment]
Yeah I can take care of this. Currently I'm just not sure whether we need to distinguish between inductors and ferrite beads, both at package level (are packages identical or not?) and on device level (do ferrite beads require a separate component/symbol indicating the ferrite core?). Unfortunately I'm not experienced enough in inductors to know whether every part is clearly either an inductor or a ferrite bead or if they cannot always be distinguished...

**Comment by eto-** [comment]
Simple ferrite beads are identical in packages (SMD or THT) to inductors.
The difference is not the presence of the ferrite (most inductors have them in any case) but the losses of the core: for inductors the core must have low losses (to preserve the field energy), for ferrite beads the high losses are wanted (to dissipate noise). 
I guess this distinction is too fine to create parallel structures: when populating the BOM the user will have to know what to use.

**Comment by ubruhin** [comment]
Alright, thanks for clarifying :+1: Sounds like we don't need to distinguish them, so I'll create just generic inductor packages + devices.

**Comment by ubruhin** [comment]
Here my suggestion for chip inductors: https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/135

Any feedback welcome! Otherwise I'll merge in a few days.

**Comment by eto-** [comment]
They looks fine: I did not experience in past inductors smaller than 0401 (IM), but having the device is harmless.

Thanks
