### ISSUE TITLE
SPDT 2 position switch component missing

### ISSUE THREAD

**Issue by Kycilak** [LibrePCB-Libraries/LibrePCB_Base.lplib#143]
Hello,
I am not able to find the switch SPDT with 2 positions in the "Add Component" window. I noticed there is a symbol in the library but no component.
Would it be possible to add it?

**Comment by ubruhin** [comment]
Good point, will be added in #144.

**Comment by ubruhin** [comment]
Should be there in a few moments, just update the base library from the library manager then.

**Comment by Kycilak** [comment]
Thank you very much. This is a wonderful project.
