### ISSUE TITLE
Add package category for switches

### ISSUE THREAD

**Issue by HBadertscher** [LibrePCB-Libraries/LibrePCB_Base.lplib#31]
Hi,

At the moment there is a (component) category for switches, but no package category. I think it would make sense to have a package category for switches too. Do you agree, or was this on purpose and switches belong somewhere else?

**Comment by ubruhin** [comment]
Hi,

One reason why I didn't add too many categories is that I'm not yet 100% sure how to handle packages which are very specific to manufacturers. Beside standardized packages like SOIC, SOT, DFN etc. there exist a huge amount of non-standardized, manufacturer specific packages. I'm just not sure if such packages should be categorized by manufacturer (inside the "Manufacturer-Specific" category), by function (e.g. "Switches"), or even both.

Anyway, probably it makes sense to add a category for switches ;)
