### ISSUE TITLE
The current IEEE 315 resistor symbol should only have 3 points on each side, not 4

### ISSUE THREAD

**Issue by hooperbloob** [LibrePCB-Libraries/LibrePCB_Base.lplib#80]
Have a look at the common results here:

https://duckduckgo.com/?q=iee315+resistor+symbol&t=chromentp&iax=images&ia=images

http://www.resistorguide.com/resistor-symbols/

While there are a few shown with four points per side, the majority show just three.

**Comment by dbrgn** [comment]
IEEE agrees:

![screenshot-20230911-132641](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/assets/105168/50ab1eed-f5e3-447c-a7af-c59dffaca743)

Not sure how much of a problem this is, but it might be worthwhile changing the symbol.
